
baseurl: ""
url: ""


# Dependencies
# markdown:         redcarpet
markdown:         kramdown
highlighter:      rouge
permalink:        pretty

title:            tkorays
tagline:          'Write code every day...'
description:      'tkorays'
url:              http://www.tkorays.com

author:
  name:           'tkorays'
  url:            http://weibo.com/tkorays

# paginate:         5

pages: [About Blog]


exclude:
    - CNAME
    - Gemfile
    - Rakefile
    - README.md
    - .gitignore
    - .sass-cache
    - Gemfile.lock
